server:
  port: 9999

# 指定当前工程所关联的Git远程地址
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:changbingbing/abcmsc-config-center.git
          # 获取到远程git库连接的超时时限，默认5S
          timeout: 5
          # 指定要操作的远程git库的分支，默认master
          default-label: master